### ISSUE TITLE
Specify numpy version >=1.19.0

### ISSUE THREAD

**Issue by nbrasher** [rtcovidlive/covid-model#17]
Installation with numpy <= 1.18.5 (latest version on anaconda), pymc3==3.9.2 and theano==1.0.4 caused compilation errors. Numpy 1.19.0 solved this. Specify numpy version in requirements.txt to avoid installation errors.

**Comment by michaelosthege** [comment]
If specifically numpy 1.18.5 causes a compilation error with a pymc3 model, please file an issue in https://github.com/pymc-devs/pymc3/issues
I'd rather specify `numpy! =1.18.5` in the PyMC3 requirements.

For Rt.live we use conda-forge to install dependencies. The test pipeline of this repo has no compilation problem.

**Comment by nbrasher** [comment]
@michaelosthege - that's helpful, I'll close and double check my setup
