### ISSUE TITLE
Proposal for better variable names

### ISSUE THREAD

**Issue by twiecki** [rtcovidlive/covid-model#2]
Proposal:
"infections" -> "transmissions", i.e. how many people transmitted the disease to someone else
"test_adjusted_positive" -> "infection_onset", i.e. how many people got infected

**Comment by k-sys** [comment]
Good to look at these. Infections are actually infections and that seems clearer to me than "transmissions" which is a synonym for longer and a bit more opaque :)

infection_onset isn't actually what's happening there, too. It is not an onset, but rather how many people would have been reported positive if testing were held constant and not noisy. I'm happy to consider other names but they still feel right-ish to me. Let me know if you'd like more clarification as it's important to get this right!
